<?php

/**
 * Laravel On-Demand Thumbnails - Sync JS Helper Command
 * 
 * @package    moonlight-poland/laravel-thumbnails
 * @author     Moonlight Poland Team <kontakt@howtodraw.pl>
 * @copyright  2024-2026 Moonlight Poland. All rights reserved.
 * @license    Commercial License - See LICENSE.md
 * @link       https://github.com/Moonlight4000/laravel-thumbnails
 * 
 * COMMERCIAL LICENSE: Free for personal use, paid for commercial use.
 * See: https://github.com/Moonlight4000/laravel-thumbnails/blob/main/LICENSE.md
 */

namespace Moonlight\Thumbnails\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\File;

class ThumbnailSyncJsCommand extends Command
{
    protected $signature = 'thumbnails:sync-js';
    
    protected $description = 'Generate JavaScript helper from thumbnails config (for React/Vue)';

    public function handle(): int
    {
        $this->info('🔄 Syncing thumbnail contexts to JavaScript...');
        
        // Read config
        $contexts = Config::get('thumbnails.contexts', []);
        $sizes = Config::get('thumbnails.sizes', []);
        $cacheFolder = Config::get('thumbnails.cache_folder', 'thumbnails');
        $filenamePattern = Config::get('thumbnails.filename_pattern', '{name}_thumb_{size}.{ext}');
        
        // Generate JS file
        $jsContent = $this->generateJsFile($contexts, $sizes, $cacheFolder, $filenamePattern);
        
        // Target path
        $targetPath = resource_path('js/utils/thumbnails.js');
        
        // Ensure directory exists
        if (!File::exists(dirname($targetPath))) {
            File::makeDirectory(dirname($targetPath), 0755, true);
        }
        
        // Write file
        File::put($targetPath, $jsContent);
        
        $this->info("✅ Generated: {$targetPath}");
        $this->comment('💡 Import in React: import { getThumbnailUrl } from \'@/utils/thumbnails\';');
        
        return self::SUCCESS;
    }
    
    protected function generateJsFile(array $contexts, array $sizes, string $cacheFolder, string $filenamePattern): string
    {
        $contextsJson = json_encode($contexts, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
        $sizesJson = json_encode(array_keys($sizes), JSON_PRETTY_PRINT);
        
        // Use single quotes to avoid PHP variable interpolation in JS code
        return <<<'JS'
/**
 * Thumbnail Helper - Auto-generated from config/thumbnails.php
 * 
 * DO NOT EDIT THIS FILE MANUALLY!
 * Run: php artisan thumbnails:sync-js
 * 
 * @package moonlight-poland/laravel-context-aware-thumbnails
 * @see https://github.com/Moonlight4000/laravel-thumbnails
 */

/**
 * Context-Aware™ path patterns
 * Source: config/thumbnails.php -> contexts
 */
export const THUMBNAIL_CONTEXTS = CONTEXTS_JSON_PLACEHOLDER;

/**
 * Available thumbnail sizes
 */
export const THUMBNAIL_SIZES = SIZES_JSON_PLACEHOLDER;

/**
 * Cache folder name (where thumbnails are stored)
 */
export const CACHE_FOLDER = 'CACHE_FOLDER_PLACEHOLDER';

/**
 * Filename pattern for thumbnails
 */
export const FILENAME_PATTERN = 'FILENAME_PATTERN_PLACEHOLDER';

/**
 * Build Context-Aware path from context name and data
 * 
 * @param {string} context - Context name (e.g., 'post', 'gallery')
 * @param {Object} contextData - Context variables (e.g., {user_id: 1, post_id: 12})
 * @returns {string|null} - Built path or null if context not found
 * 
 * @example
 * buildContextPath('post', {user_id: 1, post_id: 12})
 * // Returns: 'user-posts/1/12'
 */
export function buildContextPath(context, contextData = {}) {
    const pattern = THUMBNAIL_CONTEXTS[context];
    if (!pattern) return null;
    
    // Replace {user_id}, {post_id}, etc. with actual values
    let path = pattern;
    for (const [key, value] of Object.entries(contextData)) {
        path = path.replace(`{${key}}`, value);
    }
    
    return path;
}

/**
 * Get thumbnail URL from image path
 * Middleware will generate thumbnail on-demand if it doesn't exist (404)
 * 
 * @param {string} path - Image path (e.g., 'user-posts/1/12/img.jpg')
 * @param {string} size - Thumbnail size (small, medium, large, etc.)
 * @returns {string} - Thumbnail URL
 * 
 * @example
 * getThumbnailUrl('user-posts/1/12/img.jpg', 'small')
 * // Returns: '/storage/user-posts/1/12/thumbnails/img_thumb_small.jpg'
 */
export function getThumbnailUrl(path, size = 'small') {
    if (!path) return null;
    
    // Parse path: user-posts/1/12/img.jpg → directory + filename + extension
    const match = path.match(/^(.+)\/([^/]+)\.([^.]+)$/);
    if (!match) return `/storage/${path}`; // Fallback to original
    
    const [, directory, basename, extension] = match;
    
    // Build thumbnail URL according to pattern
    // Pattern: {name}_thumb_{size}.{ext}
    const thumbnailFilename = FILENAME_PATTERN
        .replace('{name}', basename)
        .replace('{size}', size)
        .replace('{ext}', extension);
    
    return `/storage/${directory}/${CACHE_FOLDER}/${thumbnailFilename}`;
}

/**
 * Get thumbnail URL with Context-Aware path building
 * 
 * @param {string} filename - Just the filename (e.g., 'img.jpg')
 * @param {string} size - Thumbnail size
 * @param {string} context - Context name (e.g., 'post', 'gallery')
 * @param {Object} contextData - Context variables
 * @returns {string} - Thumbnail URL
 * 
 * @example
 * getThumbnailUrlWithContext('img.jpg', 'small', 'post', {user_id: 1, post_id: 12})
 * // Returns: '/storage/user-posts/1/12/thumbnails/img_thumb_small.jpg'
 */
export function getThumbnailUrlWithContext(filename, size = 'small', context = null, contextData = {}) {
    if (!filename) return null;
    
    // Build context path if provided
    let basePath = '';
    if (context && contextData) {
        const contextPath = buildContextPath(context, contextData);
        if (contextPath) {
            basePath = contextPath + '/';
        }
    }
    
    // Parse filename
    const match = filename.match(/^(.+)\.([^.]+)$/);
    if (!match) return `/storage/${basePath}${filename}`;
    
    const [, basename, extension] = match;
    
    // Build thumbnail URL
    const thumbnailFilename = FILENAME_PATTERN
        .replace('{name}', basename)
        .replace('{size}', size)
        .replace('{ext}', extension);
    
    return `/storage/${basePath}${CACHE_FOLDER}/${thumbnailFilename}`;
}

/**
 * Default export for convenience
 */
export default {
    getThumbnailUrl,
    getThumbnailUrlWithContext,
    buildContextPath,
    THUMBNAIL_CONTEXTS,
    THUMBNAIL_SIZES,
    CACHE_FOLDER,
    FILENAME_PATTERN
};

JS;
        
        // Replace placeholders
        $js = str_replace('CONTEXTS_JSON_PLACEHOLDER', $contextsJson, $js);
        $js = str_replace('SIZES_JSON_PLACEHOLDER', $sizesJson, $js);
        $js = str_replace('CACHE_FOLDER_PLACEHOLDER', $cacheFolder, $js);
        $js = str_replace('FILENAME_PATTERN_PLACEHOLDER', $filenamePattern, $js);
        
        return $js;
    }
}

